### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by luisf350** [ChrisHodges/LightweightExcelReader#4]
Having and cell that the value is #N/A, when I move to the next column in row (ReadNextInRow()), I'm getting that exception:
![image](https://user-images.githubusercontent.com/15042693/108363489-44323780-71f5-11eb-9c48-10bc6ad45a6f.png)

I don't know if cell type as Number its the reason for that...
![image](https://user-images.githubusercontent.com/15042693/108363641-793e8a00-71f5-11eb-981c-b8fa8587bc9a.png)

**Comment by ChrisHodges** [comment]
Hi luisf350. Thanks for the bug report, it's much appreciated. This has been fixed in beta release 0.1.14:

https://github.com/ChrisHodges/LightweightExcelReader/releases/tag/v0.1.14beta

If this resolves the issue please feel free to close the issue. Let me know here if you continue to experience problems.

**Comment by luisf350** [comment]
Excellent works. You fixed it really fast. Thanks for your effort on this.
